# Trading configuration for paper/live execution

symbol: "BTC/USDT:USDT"
# Maximum total exposure (approx. notional in USDT) for this symbol
max_position_notional_usdt: 2000
# Maximum single order notional (USDT)
max_order_notional_usdt: 500
# Default percent of available USDT balance to allocate per order (0-1)
order_percent_balance: 0.2
# Leverage hint (for reference; actual leverage setting is manual in account)
leverage: 2
# Execution preferences
reduce_only: false
post_only: false
# OKX trade mode: cross or isolated
td_mode: cross
# If account in hedge mode, set pos_side to long/short; otherwise leave empty
pos_side: ""
