"""
Signal types and related data structures for the quantitative trading framework.

This module provides the signal types and data structures used across the framework.
"""

from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime
from typing import Dict, Any, Optional


class SignalType(Enum):
    """Enumeration of signal types."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class SignalStrength(Enum):
    """Enumeration of signal strengths."""
    WEAK = 1
    MODERATE = 2
    STRONG = 3


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.
    
    Attributes:
        symbol: Trading symbol
        signal_type: Type of signal (buy, sell, hold)
        strength: Signal strength
        price: Reference price
        quantity: Suggested quantity
        confidence: Confidence level (0-1)
        timestamp: Signal timestamp
        metadata: Additional signal metadata
    """
    symbol: str
    signal_type: SignalType
    strength: SignalStrength
    price: Optional[float] = None
    quantity: Optional[float] = None
    confidence: float = 0.5
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "strength": self.strength.value,
            "price": self.price,
            "quantity": self.quantity,
            "confidence": self.confidence,
            "timestamp": self.timestamp,
            "metadata": self.metadata
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Signal':
        """Create from dictionary."""
        return cls(
            symbol=data["symbol"],
            signal_type=SignalType(data["signal_type"]),
            strength=SignalStrength(data["strength"]),
            price=data.get("price"),
            quantity=data.get("quantity"),
            confidence=data.get("confidence", 0.5),
            timestamp=data.get("timestamp", datetime.now()),
            metadata=data.get("metadata", {})
        )